// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  notes: [
    'notes/notes-intro',
    {
      type: 'category',
      label: 'TypeScript',
      link: {
        type: 'generated-index',
        title: 'TypeScript 目录',
        description: "整理的一些关于 TS 的笔记，没事自己看看",
        keywords: ['TypeScript'],
      },
      items: [{
        type: 'autogenerated',
        dirName: 'notes/TypeScript'
      }],
      collapsed: false
    },
    {
      type: 'category',
      label: '设计模式',
      link: {
        type: 'generated-index',
        title: '设计模式',
        description: "TypeScript 常见设计模式，整理自 REFACTORINGGURU",
        keywords: ['guides'],
      },
      items: [{
        type: 'autogenerated',
        dirName: 'notes/pattern'
      }],
    },
    {
      label: '网络安全',
      type: 'category',
      link: {
        type: 'generated-index',
        title: '网络安全',
        description: "渗透测试，安全研发，红队相关",
        keywords: ['safety']
      },
      items: [{
        type: 'autogenerated',
        dirName: 'notes/whitehat'
      }],
      collapsed: false
    },
    {
      label: '资源',
      type: 'category',
      items: [{
        type: 'autogenerated',
        dirName: 'notes/resources'
      }],
      collapsed: false
    }
  ],
  hackfun: [
    'hackfun/hackfun-intro',
    {
      label: 'ArchLinux',
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'ArchLinux 系列',
        description: "关于 ArchLinux 日常学习、开发时，记录遇到的问题，或者有意思的地方",
        keywords: ['ArchLinux'],
      },
      items: [
        'hackfun/arch/grub',
        'hackfun/arch/timesetting',
        'hackfun/arch/rtl8812bu',
        'hackfun/arch/fancontrol',
        'hackfun/arch/bluetooth'
      ],
      collapsed: false
    },
    {
      label: 'Openwrt',
      type: 'category',
      link: {
        type: 'generated-index',
        title: 'Openwrt 系列',
        description: "关于 Openwrt 刷固件、软件包，还有一些使用备忘录",
        keywords: ['openwrt'],
      },
      items: [
        'hackfun/openwrt/installation',
        'hackfun/openwrt/turboacc',
        'hackfun/openwrt/thirdparty',
        'hackfun/openwrt/ban-ipv6'
      ],
      collapsed: false
    },
  ]
};

module.exports = sidebars;
